export interface StudentDto {
    estudianteId?: number,
    nombre: string,
    apellidoPaterno: string,
    apellidoMaterno: string,
    carnetIdentidad: string,
    fechaNacimiento: string,
    correo: string,
    genero: string,
    celular: string,
    descripcion: string,
    uuidFoto: string,
    uuidPortada: string,
    direccion: string,
    fechaRegistro: string,
    estadoCivil: string,
    username: string,
    secret: string,
    rol: string,
    semestre: number,
    colegioId: number,
    carreraId: number,
    estado: boolean
}