export interface TeacherDto {
    docenteId?: number,
    nombre: string,
    apellidoPaterno: string,
    apellidoMaterno: string,
    carnetIdentidad: string,
    fechaNacimiento: string,
    correo: string,
    genero: string,
    celular: string,
    descripcion: string,
    uuidFoto: string,
    uuidPortada: string,
    direccion: string,
    fechaRegistro: string,
    estadoCivil: string,
    username: string,
    secret: string,
    rol: string,
    tipo: string,
    profesionId: number,
    departamentoCarreraId: number,
    directorCarrera: boolean,
    estado: boolean
}